config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint(8)        not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper
  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :sex, :inclusion => { :in =>['M', 'F'] }

  def age 
    time_ago_in_words(self.birth_date)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @kitties = Cat.all
  end

  def show
    @kitty = Cat.find_by(id: params[:id])
    
    # if @kitty 
    #   render json: @kitty
    # else
    #   render json: "kitty not found"
    # end
  end

  def new
    @kitty = Cat.new
  end

  def create
    @kitty = Cat.create(cat_params)
    @kitty.save!
    render :show
  end

  def edit
    @kitty = Cat.find_by(id: params[:id])
  end

  def update
    @kitty = Cat.find_by(id: params[:id])
    Cat.update(@kitty.id, cat_params)
    render :show
  end


  private
  def cat_params
    params.require(:kitty).permit(:name, :color, :birth_date, :sex, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cats/edit.html.erb
<form action="<%= cat_url(@kitty) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <label for="name">Name: 
    <input type="text" name="kitty[name]" value="<%= @kitty.name %>">
  </label> <br>

  <label for="color">Color:
    <select name="kitty[color]">
      <option value="" disabled>-- Select a color --</option>
      <option value="Brown" <%= @kitty.color == "Brown" ? "selected" : "" %> >Brown</option>
      <option value="Black" <%= @kitty.color == "Black" ? "selected" : "" %>>Black</option>
      <option value="White" <%= @kitty.color == "White" ? "selected" : "" %>>White</option>

    </select>
  </label> <br>

  <label for="sex">Sex: 
    M<input type="radio" name="kitty[sex]" value="M" <%= @kitty.sex == "M" ? "checked" : "" %>> &emsp;
    F<input type="radio" name="kitty[sex]" value="F" <%= @kitty.sex == "F" ? "checked" : "" %>>
  </label> <br>

  <label for="birth_date">Birthday: 
    <input type="date" name="kitty[birth_date]" value="<%= @kitty.birth_date %>">
  </label> <br>

  <label for="description">Description: 
    <textarea type="textarea" name="kitty[description]" value="<%= @kitty.description %>"><%= @kitty.description %></textarea>
  </label> <br>

  <input type="submit" value="Update cat">

</form>

app/views/cats/index.html.erb
<h1>This is all the cats</h1>

<ul>
  <% @kitties.each do |kitty| %>
    <li> <%= kitty.name %> &emsp; <a href="<%= cat_url(kitty) %>">Look me up</a> </li>
    <br>
  <% end %>
</ul>

app/views/cats/new.html.erb
<form action="<%= cats_url %>" method="POST">
  <label for="name">Name: 
    <input type="text" name="kitty[name]" value="<%= @kitty.name %>">
  </label> <br>

  <label for="color">Color:
    <select name="kitty[color]">
      <option value="" selected disabled>-- Select a color --</option>
      <option value="Brown">Brown</option>
      <option value="Black">Black</option>
      <option value="White">White</option>

    </select>
  </label> <br>

  <label for="sex">Sex: 
    M<input type="radio" name="kitty[sex]" value="M"> &emsp;
    F<input type="radio" name="kitty[sex]" value="F">
  </label> <br>

  <label for="birth_date">Birthday: 
    <input type="date" name="kitty[birth_date]" value="<%= @kitty.birth_date %>">
  </label> <br>

  <label for="description">Description: 
    <textarea type="textarea" name="kitty[description]" value="<%= @kitty.description %>"></textarea>
  </label> <br>

  <input type="submit">

</form>

app/views/cats/show.html.erb
<h1>This is one cat.</h1>

<ul>
    <li> <%= @kitty.name %> </li>
    <li> <%= @kitty.birth_date %> </li>
    <li> <%= @kitty.sex %> </li>
    <li> <%= @kitty.color %> </li>
    <li> <%= @kitty.description %> </li>
    <li> <a href="<%= cats_url %>">All cats</a>  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>